version: '3'
services:
  selenoid:
    network_mode: bridge
    image: aerokube/selenoid:latest-release
    ports:
      - "4444:4444"
    volumes:
      - ".:/etc/selenoid"
      - "/var/run/docker.sock:/var/run/docker.sock"
  selenoid-ui:
    image: "aerokube/selenoid-ui"
    network_mode: bridge
    links:
      - selenoid	
    ports:
      - "8081:8080"
    command: ["--selenoid-uri", "http://selenoid:4444"]
  test:
    network_mode: bridge
    image: maven:3.8.6-amazoncorretto-11
    volumes:
      -  .:/tests
    environment:
      - MAVEN_IN_DOCKER=true
    working_dir: /tests
    links:
      - selenoid
    command: mvn clean test